### ISSUE TITLE
Patching quote problem

### ISSUE THREAD

**Issue by fbuinosquy1985** [clowdhaus/argo-cd-action#13]
Hello im trying to use this action for patching a resource and is not working , i tried with many options out there and always remove the simple quote '

```
    - name: Replacing..
      run: |
        CMD="patch-resource apps-account-activation-frontend-${{github.event.inputs.Environment}} --kind ${{github.event.inputs.Type}} --patch '{"spec": {"replicas": ${{github.event.inputs.UpDownScale}}}}'"
        echo $CMD
        echo "CMD="patch-resource apps-account-activation-frontend-${{github.event.inputs.Environment}} --kind ${{github.event.inputs.Type}} --patch '{"spec": {"replicas": ${{github.event.inputs.UpDownScale}}}}'"" >> $GITHUB_ENV
        
    - uses: clowdhaus/argo-cd-action/@main
      name: ArgoCd Scale to ${{github.event.inputs.UpDownScale}} 
      with:
        command: app
        options: '${{env.CMD}}'
```

output

/home/runner/_work/_tool/argocd/2.3.3/x64/argocd app patch-resource apps-account-activation-frontend-qa5 --kind Deployment --patch {"spec": {"replicas": 2}}
Patch resource in an application
