### ISSUE TITLE
include more detailed example

### ISSUE THREAD

**Issue by rojomisin** [clowdhaus/argo-cd-action#30]
Just trying to get going using this and the example is too simple

Would be helpful to include a working example and references on how to create an argocd service account and token using rbac, and a perhaps another example which includes an auth action using that against a server

```
      - uses: clowdhaus/argo-cd-action/@main
        env:
          ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_AUTH_TOKEN }}
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
        with:
          command: app list
          options: |
            --auth-token ${ARGOCD_AUTH_TOKEN}
            --server ${ARGOCD_SERVER}
``` 

I'm still debugging blank variables in GH actions, but if someone has a working example please post ty 🙏
